# Generated by Django 4.2.3 on 2023-08-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_subscribe_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_pk',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='id платежа в stripe'),
        ),
    ]
