# Generated by Django 4.2.3 on 2023-08-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_stripe_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_pk',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа stripe'),
        ),
    ]
