# Generated by Django 4.2.3 on 2023-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_stripe_pk_payment_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа stripe'),
        ),
    ]
