# Generated by Django 4.2.3 on 2023-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payment_stripe_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='id платежа stripe'),
        ),
    ]
