# Generated by Django 4.2.3 on 2023-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='url на видео'),
        ),
    ]
