# Generated by Django 4.2.3 on 2023-08-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_image_alter_course_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
